t(document).on("click", ".commentACT nav a", function() {
            var e = t(this).attr("data-id"),
                a = t(this).parents(".commentACT");
            t(a).find(".tabCommBody").fadeOut(100), t(a).find("." + e).slideDown(), t(a).find("nav a").removeClass("active"), t(this).addClass("active")
        }), t('<div class="commentACT">                <div class="tabCommBody commentPolicy">                <p>Silahkan tulis komentar yang sesuai dengan topik pada postingan ini.. 👌🏻</p>                    </div>                <div class="tabCommBody commentMedia" style="display:none;">                Untuk menyisipkan "Media" kedalam komentar, gunakan format <a href="https://en.wikipedia.org/wiki/BBCode" data-popWidth="1280" class="popwin" rel="external nofollow"><u>BBCode</u></a> seperti pada tabel berikut ini:                <div class="grid">                  <b>URL / TAUTAN</b><small><b>[url]</b>https://kangrian.net/<b>[/url]</b></small>                  <b>IMG / GAMBAR</b><small><b>[img]</b>https://.../gambar.jpg<b>[/img]</b></small>                  <b>YOUTUBE / VIDEO</b><small><b>[youtube]</b>https://youtu.be/id_video<b>[/youtube]</b></small>                  <b>KODE / HTML</b><small><b>[code]</b>&amp;lt;<a data-pop="#pop-parser" data-popwidth="768" title="Peralatan &gt; HTML Parser" style="text-decoration:underline;color:#009688;">parse_html</a>&amp;gt;<b>[/code]</b></small>                  </div>                  Selamat mencoba! 😁                    </div>                <nav><a href="javascript:void(0);" data-id="commentPolicy" class="active">Baca Dulu!</a><a href="javascript:void(0);" data-id="commentMedia">+ Media</a></nav>        </div>').prependTo(".comment-form, .comment-replybox-thread, .comment-replybox-single"), null != t("#commCount").val() ? t(".comment-replybox-thread .commentACT").show() : t(".comment-form .commentACT").show(), t(document).on("click", ".comment-reply", function() {
            var a = t(this).attr("data-comment-id");
            t(".commentACT").hide(), null != a ? (t("#c" + a + "-ce").find(".commentACT").show(), t("html, body").animate({
                scrollTop: t("#c" + a + "-ce").offset().top - e - 20
            }, 1e3)) : t(".comment-replybox-thread").find(".commentACT").show()
        }), t(document).ready(function() {
            if (t(".comment-content, .typography").each(function() {
                    t(this).html(t(this).html().replace(/\s:thx/gi, ' <span class="emoji">🙏</span>')), t(this).html(t(this).html().replace(/\s:\)+/g, ' <span class="emoji">🙂</span>')), t(this).html(t(this).html().replace(/\s\^(\_|)\^/g, ' <span class="emoji">😊</span>')), t(this).html(t(this).html().replace(/\s:D/g, ' <span class="emoji">😁</span>')), t(this).html(t(this).html().replace(/\s:love/gi, ' <span class="emoji">😍</span>')), t(this).html(t(this).html().replace(/\s:'\(/g, ' <span class="emoji">😥</span>')), t(this).html(t(this).html().replace(/\s;\)+/g, ' <span class="emoji">😉</span>')), t(this).html(t(this).html().replace(/\s:\|+/g, ' <span class="emoji">😑</span>')), t(this).html(t(this).html().replace(/\s:\(/g, ' <span class="emoji">😞</span>')), t(this).html(t(this).html().replace(/\sT_T/gi, ' <span class="emoji">😭</span>')), t(this).html(t(this).html().replace(/\sB\)/g, ' <span class="emoji">😎</span>')), t(this).html(t(this).html().replace(/\s:omg/gi, ' <span class="emoji">😱</span>')), t(this).html(t(this).html().replace(/\s:p/gi, ' <span class="emoji">😜</span>')), t(this).html(t(this).html().replace(/\s0:\)+/gi, ' <span class="emoji">😇</span>')), t(this).html(t(this).html().replace(/\s:v/gi, ' <span class="emoji">😆</span>')), t(this).html(t(this).html().replace(/\s:argh/gi, ' <span class="emoji">😤</span>')), t(this).html(t(this).html().replace(/\s=D/gi, ' <span class="emoji">😄</span>')), t(this).html(t(this).html().replace(/\so_O/gi, ' <span class="emoji">🙄</span>'))
                }), t(".comment-content").each(function() {
                    t(this).html(t(this).html().replace(/\[url\]/g, "<a href='").replace(/\[\/url\]/g, "' rel='nofollow' class='popwin' data-popWidth='1280'>Link</a>").replace(/\[img\]/g, "<img data-src='").replace(/\[\/img\]/g, "' />").replace(/\[code\]/g, "<pre><code>").replace(/\[\/code\]/g, "</code></pre>").replace(/\[youtube\]/g, "<a href='").replace(/\[\/youtube\]/g, "'>youtube</a>"))
                }), t("pre").each(function() {
                    t(this).prepend('<small class="dblclick"><b>Klik/tap 2x!</b> untuk menyalin..</small>')
                }), t('a[href*="https://youtu.be/"]').each(function() {
                    var e = t(this).attr("href").replace("https://youtu.be/", "");
                    t(this).addClass("cvrYoutube"), t(this).attr("data-pop", "#pop-youtube"), t(this).attr("data-popWidth", 768), t(this).attr("title", "▷ https://youtu.be/" + e), t(this).html('<img data-src="https://img.youtube.com/vi/' + e + '/maxresdefault.jpg"/><svg enable-background="new 0 0 24 24" height="512" viewBox="0 0 24 24" width="512" xmlns="https://www.w3.org/2000/svg"><path d="m.522 17.874c.49 1.738 1.989 2.056 2.089 2.117 2.467.672 16.295.674 18.799 0 1.715-.496 2.03-2.017 2.089-2.117.653-3.474.696-8.003-.03-11.945l.03.196c-.49-1.738-1.989-2.056-2.089-2.117-2.434-.661-16.298-.686-18.799 0-1.715.497-2.03 2.017-2.089 2.117-.699 3.651-.734 7.84 0 11.749zm9.086-2.223v-7.293l6.266 3.652z" fill="#e53935"/></svg>'), t(this).on("click", function(a) {
                        a.preventDefault(), t("#pop-youtube iframe").hide(), null != t("#" + e).html() ? t("#" + e).show() : t("#pop-youtube").append('<iframe id="' + e + '" src="https://youtube.com/embed/' + e + '?autoplay=1&amp;rel=0&amp;version=3&amp;enablejsapi=1&amp;playerapiid=ytplayer" allowfullscreen="allowfullscreen"></iframe>')
                    })
                }), 
